# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: spoolpra <spoolpra@student.42bangkok.co    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2022/08/26 22:57:51 by spoolpra          #+#    #+#              #
#    Updated: 2022/09/12 17:39:37 by spoolpra         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

all: vector stack map set

vector:
	@ zsh test.sh vector

stack:
	@ zsh test.sh stack

map:
	@ zsh test.sh map

set:
	@ zsh test.sh set

.PHONY: vector stack map set
